# примеры API-запросов

@baseUrl = http://127.0.0.1:8000/api

###

GET {{baseUrl}}/advertisements/


###
# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 41ebcddea436d73017c621b2cafef1ff0855fa34

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 41ebcddea436d73017c621b2cafef1ff0855fa34

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/1/
Content-Type: application/json
Authorization: Token 41ebcddea436d73017c621b2cafef1ff0855fa34

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=1
Content-Type: application/json
Authorization: Token 41ebcddea436d73017c621b2cafef1ff0855fa34

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2020-10-01
Content-Type: application/json
Authorization: Token 41ebcddea436d73017c621b2cafef1ff0855fa34
